# Generated by Django 4.2.7 on 2023-12-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('place', models.TextField()),
                ('mark', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('phoneno', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
