# Generated by Django 4.2.7 on 2023-12-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentinfo',
            new_name='StudentlistModel',
        ),
    ]
